model:
  image_size: 224
  backbone: vit_tiny_patch16_224
  proj_dim: 256

text:
  backbone: bert-base-uncased
  max_len: 16

loss:
  temperature: 0.07
  mae_weight: 1.0
  mlm_weight: 1.0
  contrastive_weight: 1.0

train:
  epochs: 25
  lr: 1.0e-5
  batch_size: 256
  weight_decay: 5.0e-2
  seed: 42
  save_dir: ""
  save_interval: 0
  data_root: /data/SSD/coco/images/
  num_workers: 8
  # Early stopping parameters
  patience: 5
  min_delta: 1.0e-4

wandb:
  enabled: true
  project: multi-mmae
  entity: augustoxq
  name: ""
  tags: [MMAE]
  notes: "多模态对比训练"
  mode: online


